#!/bin/bash
#PBS -A st-dennisjk-1
#PBS -J 1-22
#PBS -l walltime=20:00:00,select=1:ncpus=4:mem=64gb
#PBS -m be
#PBS -M willcasazza@gmail.com
################################################################################

source /home/wcasazza/miniconda3/bin/activate
conda activate ldsc
module load parallel
ldsc() {
	#/arc/project/st-dennisjk-1/software/ldsc/ldsc.py --l2 --bfile /arc/project/st-dennisjk-1/shared/data/1000G_phase3_by_chr/plink/mapped_maf01_chr${1} \
  /arc/project/st-dennisjk-1/software/ldsc/ldsc.py --l2 --bfile /arc/project/st-dennisjk-1/shared/data/1000G_EUR_ldsc_data/1000G_EUR_Phase3_plink/1000G.EUR.QC.${1} \

		--annot /scratch/st-dennisjk-1/wcasazza/1000G_phase3_ldsc/single_delahaye_annotations/${2}_${3}.${1}.annot.gz --ld-wind-cm 1 --out /scratch/st-dennisjk-1/wcasazza/1000G_phase3_ldsc/single_delahaye_annotations/${2}_${3}.${1} \
		--print-snps /arc/project/st-dennisjk-1/shared/data/1000G_EUR_ldsc_data/w_hm3.snplist
    #--print-snps /arc/project/st-dennisjk-1/shared/data/1000G_phase3_info/1kg_phase3_maf01.${1}.snplist
}

export -f ldsc
if [[ -z ${ANNOTATIONS} ]]; then
    ANNOTATIONS=("marginal" "sex_interaction")
fi

parallel ldsc ::: $PBS_ARRAY_INDEX ::: ${ANNOTATIONS[@]} ::: bin_CPP maxCPP all_cis
