#!/bin/bash
#PBS -A st-dennisjk-1
#PBS -l walltime=05:00:00,select=1:ncpus=2:mem=32gb
#PBS -m a
# N Jobs is number of GWASxnumber of mQTL setsxnumber of annotations
#PBS -J 0-48 
#PBS -j oe
#PBS -M willcasazza@gmail.com
################################################################################
GWAS=( adhd_jul2017 CAD_META rall_SCZ ukbb_preeclampsia_female AD_jansen_2019 IBS_Bonfiglio ukbb_preeclampsia_both_sexes iPSYCH-PGC_ASD_Nov2017 )
MQTL=( marginal sex_interaction )
ANNOTATION=( all_cis bin_CPP maxCPP )

GWAS_N=${#GWAS[@]}
MQTL_N=${#MQTL[@]}
ANNOTATION_N=${#ANNOTATION[@]}

CUR_GWAS=${GWAS[$((${PBS_ARRAY_INDEX}%${GWAS_N}))]}
CUR_MQTL=${MQTL[$((${PBS_ARRAY_INDEX}%${MQTL_N}))]}
CUR_ANNOTATION=${ANNOTATION[$((${PBS_ARRAY_INDEX}%${ANNOTATION_N}))]}
source /home/wcasazza/miniconda3/bin/activate
conda activate ldsc

ldsc() {
	/arc/project/st-dennisjk-1/software/ldsc/ldsc.py --h2 /scratch/st-dennisjk-1/wcasazza/tmp_GWAS/formatted_sumstats/${1}.sumstats.gz \
		--ref-ld-chr /scratch/st-dennisjk-1/wcasazza/1000G_phase3_ldsc/single_delahaye_annotations/${2}_${3}.,/scratch/st-dennisjk-1/wcasazza/1000G_phase3_ldsc/baseline_annot_files/fixed_baselineLD. --w-ld-chr /scratch/st-dennisjk-1/wcasazza/1000G_phase3_ldsc/weights_1kg_common/1kg_cosmopolitan.common. --frqfile-chr /arc/project/st-dennisjk-1/shared/data/1000G_phase3_by_chr/plink/mapped_maf01_chr --out /scratch/st-dennisjk-1/wcasazza/delahaye_QC/ldsc_results/${2}_${3}_${1} \
		--overlap-annot \
		--print-coefficients \
		--print-delete-vals
}

ldsc ${CUR_GWAS} ${CUR_MQTL} ${CUR_ANNOTATION}
