#!/bin/bash

#PBS -l walltime=05:00:00,select=1:ncpus=20:mem=100gb
#PBS -N mqtl_chr
#PBS -A st-dennisjk-1
#PBS -m abe
#PBS -M willcasazza@gmail.com
cd /scratch/st-dennisjk-1/wcasazza/delahaye_QC/
module load singularity
singularity exec /arc/project/st-dennisjk-1/software/rstudio/rstudio.sif Rscript run_cis_mqtl_75k.R --data_dir="matrix_eqtl_data/" \
	--SNP_fname="all_imputed_matrixeQTL${sex}.txt" \
	--cov_file="mQTL_covar_9_methy_PC${sex}.txt" \
	--cis_outfile="${outfile}" \
	--snp_pos="snp_pos.txt" \
	--methylation_fname="methylation_matrixeQTL${sex}.txt" \
	--probe_pos="probe_pos.txt" \
	--model="${model}"
