#!/bin/bash

#PBS -l walltime=10:00:00,select=1:ncpus=32:mem=60gb
#PBS -N caviar_merge
#PBS -A st-dennisjk-1
#PBS -m abe
#PBS -M willcasazza@gmail.com
#PBS -j oe
#PBS -J 1-22
################################################################################
cd /scratch/st-dennisjk-1/wcasazza/sex_specific_mQTL/delahaye_mQTL_analyses/r_scripts/

# Load software environment

module load r

Rscript merge_caviar.R $PBS_ARRAY_INDEX $Z_DIR $FILE_PREFIX

Rscript match_annotation_baseline.R "${FILE_PREFIX}.%d.annot.gz" "${FILE_PREFIX}_%s.%d.annot.gz"

Rscript make_cis_annotation.R ${MQTL} "${FILE_PREFIX}.%d.annot.gz" "${FILE_PREFIX}_all_cis"
