#!/bin/bash

#PBS -l walltime=03:00:00,select=1:ncpus=16:mem=60gb
#PBS -N caviar_z_score
#PBS -A st-dennisjk-1
#PBS -m abe
#PBS -M willcasazza@gmail.com

################################################################################

cd /scratch/st-dennisjk-1/wcasazza/delahaye_QC/
module load singularity
export SINGULARITYENV_LD_LIBRARY_PATH="/usr/local/lib/R/lib:/usr/local/lib:/usr/lib/x86_64-linux-gnu:/usr/lib/jvm/java-11-openjdk-amd64/lib/server:/arc/software/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-5.4.0-mufy3fjs33jgj47lb3346bqktgtjnt4i/lib64:/arc/software/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-5.4.0-mufy3fjs33jgj47lb3346bqktgtjnt4i/lib:/cm/shared/apps/pbspro-ce/19.1.3/lib:/.singularity.d/libs":$LD_LIBRARY_PATH
# Execute the rserver within the rocker/rstudio container
singularity exec --bind $TMPDIR:/var/run --home /scratch/st-dennisjk-1/wcasazza/ /arc/project/st-dennisjk-1/software/rstudio/rstudio.sif Rscript prep_caviar_z.R
