#!/bin/bash
#PBS -A st-dennisjk-1
#PBS -l walltime=04:00:00,select=1:ncpus=16:mem=64gb
#PBS -m be
#PBS -M willcasazza@gmail.com
################################################################################

source /home/wcasazza/miniconda3/bin/activate
conda activate ldsc
module load parallel
ldsc() {
  /arc/project/st-dennisjk-1/software/ldsc/ldsc.py\
    --h2 /scratch/st-dennisjk-1/wcasazza/tmp_GWAS/formatted_sumstats/${1}.sumstats.gz \
    --ref-ld-chr /scratch/st-dennisjk-1/wcasazza/1000G_phase3_ldsc/partitioned_1kg_common/merged_sex_interaction_marginal.\
    --overlap-annot \
    --w-ld-chr /scratch/st-dennisjk-1/wcasazza/1000G_phase3_ldsc/weights_1kg_common/1kg_cosmopolitan.common.\
    --frqfile-chr /arc/project/st-dennisjk-1/shared/data/1000G_phase3_by_chr/plink/mapped_chr.\
    --out /scratch/st-dennisjk-1/wcasazza/delahaye_QC/ldsc_results/merged_${1}\
    --print-coefficients \
    --print-delete-vals
}

export -f ldsc
parallel ldsc ::: adhd_jul2017 CAD_META rall_SCZ ukbb_preeclampsia_female AD_jansen_2019 IBS_Bonfiglio ukbb_preeclampsia_both_sexes
