#!/bin/bash

#PBS -l walltime=01:00:00,select=1:ncpus=16:mem=64gb
#PBS -N my_rstudio_server
#PBS -A st-dennisjk-1
#PBS -m abe
#PBS -M willcasazza@gmail.com
#PBS -j oe
################################################################################

# Change directory into the job dir
cd $PBS_O_WORKDIR

# Load software environment
module load singularity
module load gsl
module load netlib-lapack
module load netlib-xblas
# Set RANDFILE location to writeable dir
export RANDFILE=$TMPDIR/.rnd
# Generate a unique password for RStudio Server
export SINGULARITYENV_PASSWORD=$(openssl rand -base64 15)

# Find a unique port for RStudio Server to listen on
readonly PORT=$(python -c 'import socket; s=socket.socket(); s.bind(("", 0)); print(s.getsockname()[1]); s.close()')

# Set per-job location for the rserver secure cookie
export SECURE_COOKIE=$TMPDIR/secure-cookie-key

# Print connection details to file
cat >connection_${PBS_JOBID}.txt <<END

1. Create an SSH tunnel to RStudio Server from your local workstation using the following command:

ssh -N -L 8787:${HOSTNAME}:${PORT} ${USER}@sockeye.arc.ubc.ca

2. Point your web browser to http://localhost:8787

3. Login to RStudio Server using the following credentials:

Username: ${USER}
Password: ${SINGULARITYENV_PASSWORD}

When done using RStudio Server, terminate the job by:

1. Sign out of RStudio (Left of the "power" button in the top right corner of the RStudio window)
2. Issue the following command on the login node:

qdel ${PBS_JOBID}

END

export SINGULARITYENV_LD_LIBRARY_PATH="/usr/local/lib/R/lib:/usr/local/lib:/usr/lib/x86_64-linux-gnu:/usr/lib/jvm/java-11-openjdk-amd64/lib/server:/arc/software/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-5.4.0-mufy3fjs33jgj47lb3346bqktgtjnt4i/lib64:/arc/software/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-5.4.0-mufy3fjs33jgj47lb3346bqktgtjnt4i/lib:/cm/shared/apps/pbspro-ce/19.1.3/lib:/.singularity.d/libs":$LD_LIBRARY_PATH
# Execute the rserver within the rocker/rstudio container
singularity exec --bind $TMPDIR:/var/run --home /scratch/st-dennisjk-1/wcasazza/ /arc/project/st-dennisjk-1/software/rstudio/rstudio.sif rserver --auth-none=0 --auth-pam-helper-path=pam-helper --secure-cookie-key-file ${SECURE_COOKIE} --www-port ${PORT}
