#!/bin/bash
#PBS -A st-dennisjk-1
#PBS -l walltime=10:00:00,select=1:ncpus=32:mem=182gb
#PBS -J 1-24

#PBS -j oe
################################################################################


module load singularity

singularity exec /arc/project/st-dennisjk-1/software/jupyter/jupyter-datascience.sif Rscript /scratch/st-dennisjk-1/wcasazza/sex_specific_mQTL/delahaye_mQTL_analyses/r_scripts/placental_mqtl_colocalization.R $COHORT $PBS_ARRAY_INDEX $MQTL
